# Generated by Django 5.2 on 2025-05-12 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'body_type',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'city',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'drive_type',
            },
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_consumption', models.DecimalField(decimal_places=1, max_digits=4)),
                ('highway_consumption', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mixed_consumption', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            options={
                'db_table': 'fuel_consumption',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'fuel_type',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'transmission_type',
            },
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'transport_type',
            },
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advert',
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favourite',
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_models', to='advert.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.model')),
            ],
            options={
                'db_table': 'brand_model',
                'unique_together': {('brand', 'model')},
            },
        ),
        migrations.CreateModel(
            name='RegionCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_cities', to='advert.region')),
            ],
            options={
                'db_table': 'region_city',
                'unique_together': {('region', 'city')},
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='region_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.regioncity'),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3)),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('owners_number', models.PositiveSmallIntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.bodytype')),
                ('brand_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.brandmodel')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.color')),
                ('drive_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.drivetype')),
                ('fuel_consumption', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='advert.fuelconsumption')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.fueltype')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.transmissiontype')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.transporttype')),
            ],
            options={
                'db_table': 'transport',
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='transport',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='advert.transport'),
        ),
        migrations.CreateModel(
            name='TransportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transports/%Y/%m/%d')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advert.transport')),
            ],
            options={
                'db_table': 'transport_photo',
            },
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['slug'], name='advert_slug_5f7893_idx'),
        ),
    ]
