# Generated by Django 5.2 on 2025-04-18 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriveWheelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.DecimalField(decimal_places=1, max_digits=4)),
                ('highway', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mixed', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=3)),
                ('engine_power', models.PositiveSmallIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('owners_number', models.PositiveSmallIntegerField()),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.bodytype')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.color')),
                ('drive_wheel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.drivewheeltype')),
                ('fuel_consumption', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.fuelconsumption')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.fueltype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.model')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.transmissiontype')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advert.transporttype')),
            ],
        ),
        migrations.CreateModel(
            name='TransportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transports/%Y/%m/%d')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advert.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
                ('transport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advert.transport')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='advert_adve_slug_fb773e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['id'], name='advert_tran_id_129293_idx'),
        ),
    ]
