# Generated by Django 5.1.4 on 2024-12-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='transports/%Y/%m/%d')),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mileage', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('propeller_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('seat_number', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('transport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.transport')),
                ('load_capacity', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('main.transport',),
        ),
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
                ('transport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.transport')),
            ],
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['id'], name='main_transp_id_c3e289_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['title'], name='main_transp_title_e1b7df_idx'),
        ),
        migrations.AddIndex(
            model_name='advert',
            index=models.Index(fields=['slug'], name='main_advert_slug_2a371e_idx'),
        ),
    ]
